# Generated by Django 5.0.6 on 2024-05-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipCode', models.CharField(max_length=300)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('order_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date_added'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
